name: Rho test site
favicon: null
layout_spectrum: 0.9393764126580209
typography_spectrum: 0.7312140280846506
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebedef'
    - '#5ebce3'
    - '#000316'
    - '#5a7a58'
    - '#0074a5'
  brandStrength: 0.8155605820938945
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
