name: Rho test site
favicon: null
layout_spectrum: 0.1668
typography_spectrum: 0.7312140280846506
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dedede'
    - '#14161a'
    - '#8b8984'
    - '#00a651'
    - '#cc2831'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
